### ISSUE TITLE
Depth-map reduced to white in output

### ISSUE THREAD

**Issue by YanWittmann** [AnonymousCervine/depth-image-io-for-SDWebui#5] opened 2023-02-01 18:49 UTC
I seem to have some trouble getting this extension to work;

I use the `512-depth-ema.ckpt` with an according `512-depth-ema.yaml` file, which works in img2img. When I ask the UI to generate an image on the text2img tab with the extension script active, the depth map is reduced to almost white however:

![grafik](https://user-images.githubusercontent.com/37689635/216134438-e06d8911-10e1-4484-a4dd-ccedde5943a1.png)

And the whole UI:

![grafik](https://user-images.githubusercontent.com/37689635/216133889-088b5db5-b9c6-4cd5-b9b3-311f5afd94ae.png)

The error might very well be on my part, can someone tell me where I went wrong? Thank you!

Details:

- Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
- latest version of the Automatic UI (226d840e84c5f306350b0681945989b86760e616)

**Comment by AnonymousCervine** [comment] 2023-02-02 01:46
There have been reported issues with different image formats already (namely, issue #2 ); by any chance can you give me a copy of the file used for the input depth image here?

(It almost certainly isn't going to be a problem with the configuration in this case. Based on that screenshot, the extension isn't parsing the input depth image correctly.)

**Comment by YanWittmann** [comment] 2023-02-02 07:25
Ah, the image format. All right, I got it to work

- by converting the image into a JPG
- by reexporting the image from an image editor as PNG

Here's the original PNG:

![PNG before](https://user-images.githubusercontent.com/37689635/216257937-01e597d0-a5ab-442b-b56e-d271fee18060.png)

And here's the re-exported PNG version:

![PNG after](https://user-images.githubusercontent.com/37689635/216258048-b61407b4-bacf-4ec0-a023-35164ecd5772.png)

Here are some results for `The face of a young man, highly detailed photography`

![grafik](https://user-images.githubusercontent.com/37689635/216258134-47b3377b-b2c8-4dc9-ba5f-a8b06d56de5e.png)

I am having some trouble adding a red shirt however, do you have any suggestions on how to not make the entire face red (which is the case for almost every generation I make with this prompt)? `The face of a young man, highly detailed photography wearing a red shirt`

![grafik](https://user-images.githubusercontent.com/37689635/216258441-c8a56249-035a-4b4c-9628-8b590602b245.png)

Thank you!

**Comment by AnonymousCervine** [comment] 2023-02-04 02:29
First, thank you for the source images, they're most helpful!

Since it does seem to be the same format problem, I'm going to mark this issue as a duplicate of #2 (any updates will be posted there)

> I am having some trouble adding a red shirt however, do you have any suggestions on how to not make the entire face red 

I too have noticed that the depth2img model is honestly a little bit wonky about prompts sometimes compared to normal SD models we're used to—perhaps *especially* with regard to colours.

Depending on your goals: You can always do it in two steps and use inpaint! There is a bug where SD doesn't handle inpainting correctly for depth2img but if you supply the depth manually with this extension (i.e. the same depth image, again) it will respect it. (Though it will still may have that certain "I am inpainted" look; on the other hand, it doesn't get the general structure of things wrong as much as normal inpainting because it has the depth to guide it.)

So for instance, using your first prompt and getting this (emulated stock-photo bands and all! And strikingly similar to the image you got, really. I do wonder if in general the structure provided by the depth half of depth2img model-input doesn't make SD a little less creative sometimes):

![image](https://user-images.githubusercontent.com/118340091/216741234-24199b95-05cd-4626-b9e2-a49755797229.png)

Masked like so:

![image](https://user-images.githubusercontent.com/118340091/216741289-50fb041c-db05-4354-b612-e235d653cd8e.png)

With prompt "a young man wearing a (red:1.2) shirt" (emphasis only on the things inpainting needs to know, and you'll notice I had trouble getting it to pick *up* the idea of 'red' again in an image without it); cherry-picked best result out of 12-ish:

![image](https://user-images.githubusercontent.com/118340091/216741386-32331d8c-1009-4000-bfc6-ba909f951658.png)

(Note that it's still following the shoulder contours suggested by the depth image. Otherwise, it's just a normal-ish inpainting job.)

**Closed as completed** 2023-02-04 02:29 UTC
Labels: duplicate
